/// Flutter icons AppIconAdmin
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIconAdmin
///      fonts:
///       - asset: fonts/AppIconAdmin.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIconAdmin {
  AppIconAdmin._();

  static const _kFontFam = 'AppIconAdmin';
  static const String? _kFontPkg = null;

  static const IconData admin = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_admin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
