/// Flutter icons CarCustom
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CarCustom
///      fonts:
///       - asset: fonts/CarCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CarCustom {
  CarCustom._();

  static const _kFontFam = 'CarCustom';
  static const String? _kFontPkg = null;

  static const IconData mchs__1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData depositphotos_197533148_stock_illustration_car_top_view_transportation_vector = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData policce = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
